require 'vagrant-ansible'

Vagrant::Config.run do |config|
  config.vm.box = "precise64"

  config.vm.forward_port 80, 8080
  
  config.vm.provision :ansible do |ansible|
    # point Vagrant at the location of your playbook you want to run
    ansible.playbook = "vagrant-ubuntu.yml"

    # the Vagrant VM will be put in this host group change this should
    # match the host group in your playbook you want to test
    ansible.hosts = "vagrant-web-servers"

  end
end
