---
- hosts: vagrant-web-servers
  user: vagrant
  sudo_user: postgres
  sudo: True

  tasks:
    - name: create database
      postgresql_db: name=$database_name state=present
    
    - name: create postgres user
      postgresql_user: db=$database_name user=$database_user password=$database_password role_attr_flags=NOCREATEDB,NOSUPERUSER state=present

    - name: install postgres config file
      template: src=../templates/postgresql.j2 dest=/etc/postgresql/9.1/main/postgresql.conf
      notify:
        - restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

- hosts: vagrant-web-servers
  user: vagrant
  sudo: True

  tasks:
    - name: configure postgres service
      service: name=postgresql enabled=yes state=started
